// Builds sprites.js, the list of PNG filenames Derby Dash picks from.
//
// Usage (from anywhere):   node build-sprites.js
// Re-run it whenever you add or remove PNGs in the sprites/ folder.

const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "sprites");
const out = path.join(__dirname, "sprites.js");

if (!fs.existsSync(dir)) {
  console.error("Can't find the sprites folder:\n  " + dir + "\nCreate it and put your PNGs inside.");
  process.exit(1);
}

const files = fs.readdirSync(dir).filter((f) => /\.png$/i.test(f)).sort();

const body =
  "// Auto-generated by build-sprites.js. Don't edit by hand; re-run the script instead.\n" +
  "window.DERBY_SPRITES = " + JSON.stringify(files, null, 2) + ";\n";

fs.writeFileSync(out, body);
console.log("Wrote " + files.length + " sprites to " + out);
