"""Builds sprites.js, the list of PNG filenames Derby Dash picks from.

Usage (from anywhere):   python build_sprites.py
Re-run it whenever you add or remove PNGs in the sprites/ folder.
"""
import json
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
sprite_dir = here / "sprites"
out = here / "sprites.js"

if not sprite_dir.is_dir():
    sys.exit(f"Can't find the sprites folder:\n  {sprite_dir}\nCreate it and put your PNGs inside.")

files = sorted(p.name for p in sprite_dir.iterdir() if p.suffix.lower() == ".png")

out.write_text(
    "// Auto-generated by build_sprites.py. Don't edit by hand; re-run the script instead.\n"
    "window.DERBY_SPRITES = " + json.dumps(files, indent=2) + ";\n",
    encoding="utf-8",
)
print(f"Wrote {len(files)} sprites to {out}")
