(function () {
  // Remember where this script lives. document.currentScript only exists while the
  // script is first running, so it has to be read here, not later. Sprite paths are
  // resolved against it so they work from games/derby-dash.html AND from the copy
  // embedded in ../index.html.
  var SCRIPT_SRC = document.currentScript && document.currentScript.src;

  // Folder (next to this file) that holds the PNGs.
  var SPRITE_DIR = "sprites/";

  // Filename list generated by build-sprites.js / build_sprites.py into sprites.js.
  // If it's missing or empty, the game falls back to the emoji horses.
  var SPRITES = Array.isArray(window.DERBY_SPRITES) ? window.DERBY_SPRITES : [];

  var HORSES = [
    { name: "Horse 1",    emoji: "🐎" },
    { name: "Horse 2",    emoji: "🐴" },
    { name: "Horse 3",    emoji: "🐎" },
    { name: "Horse 4",    emoji: "🐴" },
    { name: "Horse 5",    emoji: "🐎" }
  ];

  var track = document.getElementById("track");
  var startBtn = document.getElementById("startBtn");
  var resetBtn = document.getElementById("resetBtn");
  var status = document.getElementById("status");

  var laneEls = [];
  var raceInterval = null;
  var positions = [];
  var finished = false;

  var upcoming = null;      // next lineup, picked early so its images can preload
  var preloaded = [];       // keeps preload requests alive until they finish
  var lineupRaced = false;  // true once the lineup on screen has been raced

  var FINISH_PCT = 100; // percent of usable lane width

  /* ---------- sprites ---------- */

  function spriteUrl(file) {
    var rel = SPRITE_DIR + encodeURIComponent(file);
    try {
      return new URL(rel, SCRIPT_SRC || document.baseURI).href;
    } catch (e) {
      return rel;
    }
  }

  // Random, non-repeating selection (Fisher-Yates shuffle, then take the first `count`).
  // Returns fewer than `count` if there aren't enough sprites; the rest use emoji.
  function pickSprites(count) {
    var pool = SPRITES.slice();
    for (var i = pool.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = pool[i];
      pool[i] = pool[j];
      pool[j] = tmp;
    }
    return pool.slice(0, count);
  }

  function preload(files) {
    preloaded = files.map(function (file) {
      var img = new Image();
      img.src = spriteUrl(file);
      return img;
    });
  }

  // Returns the lineup to use now, and lines up + preloads the one after it,
  // so the next race's images are already cached when you press Start.
  function nextLineup() {
    var lineup = upcoming || pickSprites(HORSES.length);
    upcoming = pickSprites(HORSES.length);
    preload(upcoming);
    return lineup;
  }

  // Put a sprite (or the emoji, if there's no file / it fails to load) in a horse element.
  function showHorse(horseEl, horse, file) {
    horseEl.textContent = "";
    horseEl.classList.remove("sprite");
    if (!file) {
      horseEl.textContent = horse.emoji;
      return;
    }
    var img = document.createElement("img");
    img.alt = "";
    img.draggable = false;
    img.decoding = "async";
    img.addEventListener("error", function () {
      // Ignore if this lane has already been given a newer sprite.
      if (img.parentNode === horseEl) showHorse(horseEl, horse, null);
    });
    img.src = spriteUrl(file);
    horseEl.classList.add("sprite");
    horseEl.appendChild(img);
  }

  function dealLineup() {
    var files = nextLineup();
    laneEls.forEach(function (el, i) {
      showHorse(el, HORSES[i], files[i]);
    });
  }

  /* ---------- track ---------- */

  function buildTrack() {
    var existing = track.querySelectorAll(".lane");
    existing.forEach(function (el) { el.remove(); });

    laneEls = HORSES.map(function (h, i) {
      var lane = document.createElement("div");
      lane.className = "lane";

      var label = document.createElement("span");
      label.className = "lane-label";
      label.textContent = i + 1;
      lane.appendChild(label);

      var horse = document.createElement("span");
      horse.className = "horse";
      // Dynamic left-position is set via JS during the race; this is
      // required for the per-frame animation and can't be expressed
      // as a static CSS class without one class per pixel position.
      horse.style.left = "4px";
      lane.appendChild(horse);

      track.appendChild(lane);
      return horse;
    });
  }

  function resetRace() {
    clearInterval(raceInterval);
    raceInterval = null;
    finished = false;
    positions = HORSES.map(function () { return 0; });
    laneEls.forEach(function (el) {
      el.classList.remove("winner");
      el.style.left = "4px";
    });
    dealLineup();
    lineupRaced = false;
    status.textContent = "";
    startBtn.disabled = false;
    resetBtn.disabled = true;
  }

  function laneMaxPx(horseEl) {
    // Sprites vary in width, so measure them; emoji keep the original fixed gutter.
    var gutter = horseEl.classList.contains("sprite")
      ? Math.max(horseEl.offsetWidth, 24) + 14
      : 44; // horse width + finish gutter
    return horseEl.parentElement.clientWidth - gutter;
  }

  function startRace() {
    if (raceInterval) return;
    // The lineup on screen is fresh after load/reset; after a finished race, draw a new one.
    if (lineupRaced) dealLineup();
    lineupRaced = true;

    finished = false;
    positions = HORSES.map(function () { return 0; });
    laneEls.forEach(function (el) {
      el.classList.remove("winner");
      el.style.left = "4px";
    });
    status.textContent = "They're off!";
    startBtn.disabled = true;
    resetBtn.disabled = false;

    raceInterval = setInterval(function () {
      if (finished) return;

      var winnerIdx = -1;

      positions = positions.map(function (pos, i) {
        var step = Math.random() * 3.2 + 0.6; // randomized speed
        var next = Math.min(pos + step, FINISH_PCT);
        var laneEl = laneEls[i];
        var maxPx = laneMaxPx(laneEl);
        laneEl.style.left = (4 + (next / FINISH_PCT) * maxPx) + "px";
        if (next >= FINISH_PCT && winnerIdx === -1) winnerIdx = i;
        return next;
      });

      if (winnerIdx !== -1) {
        finished = true;
        clearInterval(raceInterval);
        raceInterval = null;
        laneEls[winnerIdx].classList.add("winner");
        status.textContent = HORSES[winnerIdx].name + " (lane " + (winnerIdx + 1) + ") wins the race!";
        startBtn.disabled = false;
        resetBtn.disabled = false;
      }
    }, 90);
  }

  startBtn.addEventListener("click", startRace);
  resetBtn.addEventListener("click", resetRace);

  buildTrack();
  resetRace();
})();
