// Auto-generated by build-sprites.js. Don't edit by hand; re-run the script instead.
// (Empty for now: the game uses the emoji horses until you generate this from your PNG folder.)
window.DERBY_SPRITES = [];
